-- Seed experiences with real-looking data
-- We reference region_id and category_id by subquery since UUIDs are auto-generated

insert into public.experiences (title, slug, excerpt, description, region_id, category_id, price_cents, original_price_cents, duration_hours, max_guests, min_age, rating, review_count, featured, best_seller, image_url, gallery, includes, excludes, highlights, meeting_point, status)
values
(
  'Ruta de los Flysch en Zumaia',
  'ruta-flysch-zumaia',
  'Recorre los acantilados mas espectaculares de la costa vasca con guias geologos expertos.',
  'Descubre los impresionantes acantilados de flysch de Zumaia, declarados Geoparque Mundial por la UNESCO. Esta experiencia unica te llevara por un recorrido costero de 5 horas donde un geologo experto te explicara 60 millones de anos de historia de la Tierra grabados en las capas de roca. Caminaras por senderos sobre los acantilados con vistas al Cantabrico, bajaras a calas escondidas y entenderas por que este lugar fue escenario de la serie Juego de Tronos. Incluye picnic con productos locales en un mirador privilegiado.',
  (select id from public.regions where slug = 'pais-vasco'),
  (select id from public.categories where slug = 'ecoturismo'),
  7500,
  8900,
  5,
  12,
  8,
  4.8,
  127,
  true,
  true,
  'https://images.unsplash.com/photo-1597225244660-1cd128c64284?w=800&q=80',
  array['https://images.unsplash.com/photo-1597225244660-1cd128c64284?w=800&q=80', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80'],
  array['Guia geologo certificado', 'Picnic con productos locales', 'Seguro de actividad', 'Bastones de senderismo'],
  array['Transporte hasta el punto de encuentro', 'Calzado de senderismo (recomendado traer propio)'],
  array['Acantilados UNESCO Geoparque', 'Picnic con vistas al Cantabrico', 'Guia geologo experto', 'Calas escondidas'],
  'Oficina de Turismo de Zumaia, Plaza Zuloaga',
  'active'
),
(
  'Agroturismo en caserio vasco',
  'agroturismo-caserio-vasco',
  'Vive un dia completo en un caserio tradicional: ordena ovejas, elabora queso y disfruta de un almuerzo casero.',
  'Sumérgete en la vida rural vasca pasando un dia completo en un autentico caserio del siglo XVII en las colinas de Aia. Comenzaras al amanecer con la recogida de las ovejas latxas, aprenderas a ordenarlas y participaras en la elaboracion del famoso queso Idiazabal. Tras una manana de trabajo en el campo, disfrutaras de un almuerzo preparado con productos de la propia finca: sidra natural, chuleton a la brasa y tarta de queso. Una experiencia autentica que conecta con las raices del Pais Vasco.',
  (select id from public.regions where slug = 'pais-vasco'),
  (select id from public.categories where slug = 'agroturismo'),
  9500,
  null,
  8,
  8,
  6,
  4.9,
  89,
  true,
  false,
  'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&q=80',
  array['https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&q=80', 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800&q=80'],
  array['Almuerzo completo con bebidas', 'Guia bilingue', 'Delantal y material para el taller', 'Queso artesanal para llevar a casa'],
  array['Transporte al caserio', 'Ropa de campo'],
  array['Ordeno de ovejas latxas', 'Taller de queso Idiazabal', 'Almuerzo casero con sidra', 'Caserio del siglo XVII'],
  'Caserio Igartubeiti, Ezkio-Itsaso, Gipuzkoa',
  'active'
),
(
  'Kayak en los acantilados de Gaztelugatxe',
  'kayak-gaztelugatxe',
  'Rema bajo los acantilados de San Juan de Gaztelugatxe y explora cuevas marinas inaccesibles a pie.',
  'Una aventura maritima unica: partiras desde la playa de Bakio en kayaks de mar dobles y remararas a lo largo de la impresionante costa hasta la ermita de San Juan de Gaztelugatxe. Durante el recorrido, tu monitor te guiara a traves de cuevas marinas, arcos de roca y piscinas naturales formadas por la erosion. Pararas en una cala secreta para un tentempie y podras banarte en aguas cristalinas. Nivel medio de dificultad, no se requiere experiencia previa.',
  (select id from public.regions where slug = 'pais-vasco'),
  (select id from public.categories where slug = 'turismo-activo'),
  6500,
  null,
  4,
  8,
  14,
  4.7,
  65,
  false,
  true,
  'https://images.unsplash.com/photo-1472745433479-4556f22e32c2?w=800&q=80',
  array['https://images.unsplash.com/photo-1472745433479-4556f22e32c2?w=800&q=80', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80'],
  array['Kayak doble y equipo completo', 'Monitor titulado', 'Neopreno y chaleco', 'Tentempie y agua', 'Fotos de la actividad'],
  array['Transporte a Bakio', 'Toalla'],
  array['Cuevas marinas secretas', 'Vistas a Gaztelugatxe desde el mar', 'Bano en calas cristalinas', 'Fotos incluidas'],
  'Playa de Bakio, puesto de Wakalea Aventura',
  'active'
),
(
  'Senderismo en el Caminito del Rey',
  'senderismo-caminito-del-rey',
  'Atraviesa la pasarela mas espectacular de Espana suspendida sobre el Desfiladero de los Gaitanes.',
  'Vive la experiencia del Caminito del Rey, una de las rutas de senderismo mas espectaculares del mundo. Recorreras pasarelas suspendidas a mas de 100 metros de altura sobre el rio Guadalhorce, cruzaras un puente colgante de 30 metros y atravesaras tuneles excavados en la roca. Nuestro guia naturalista te descubrira la fauna y flora del desfiladero: buitres leonados, cabras montesas y orquideas silvestres. La experiencia incluye transporte desde Malaga y un almuerzo tipico en El Chorro.',
  (select id from public.regions where slug = 'andalucia'),
  (select id from public.categories where slug = 'turismo-activo'),
  5900,
  6900,
  6,
  15,
  10,
  4.9,
  214,
  true,
  true,
  'https://images.unsplash.com/photo-1501555088652-021d21d0d6df?w=800&q=80',
  array['https://images.unsplash.com/photo-1501555088652-021d21d0d6df?w=800&q=80', 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80'],
  array['Entrada al Caminito del Rey', 'Guia naturalista oficial', 'Casco de seguridad', 'Transporte Malaga-El Chorro', 'Almuerzo tipico'],
  array['Calzado de senderismo (obligatorio)', 'Proteccion solar'],
  array['Pasarelas a 100m de altura', 'Puente colgante de 30m', 'Buitres leonados en vuelo', 'Almuerzo en El Chorro'],
  'Estacion de autobuses de Malaga, puerta 12',
  'active'
),
(
  'Ruta del olivo milenario en Maestrazgo',
  'ruta-olivo-milenario-maestrazgo',
  'Visita olivos de mas de 1000 anos, participa en la recogida y cata aceites premium de la Comunidad Valenciana.',
  'En las tierras del Maestrazgo castellonense se esconden algunos de los olivos mas antiguos del mundo, arboles milenarios que ya daban fruto cuando los romanos construian acueductos. Esta experiencia te sumerge en el mundo del aceite de oliva virgen extra: recorreras fincas con olivos monumentales, aprenderas las tecnicas de recogida tradicional (vareado) y moderna, visitaras una almazara artesanal y terminaras con una cata guiada de 5 aceites monovarietales maridados con pan de lena y embutidos locales.',
  (select id from public.regions where slug = 'comunidad-valenciana'),
  (select id from public.categories where slug = 'agroturismo'),
  4900,
  null,
  5,
  10,
  0,
  4.6,
  43,
  false,
  false,
  'https://images.unsplash.com/photo-1501004318855-fce86ee188a8?w=800&q=80',
  array['https://images.unsplash.com/photo-1501004318855-fce86ee188a8?w=800&q=80', 'https://images.unsplash.com/photo-1474979266404-7f28db37f20a?w=800&q=80'],
  array['Guia agroalimentario', 'Visita a almazara', 'Cata de 5 aceites', 'Aperitivo con productos locales', 'Botella de AOVE de regalo'],
  array['Transporte a la finca', 'Comida completa (solo aperitivo incluido)'],
  array['Olivos de mas de 1000 anos', 'Cata de 5 aceites premium', 'Visita a almazara artesanal', 'Botella de AOVE de regalo'],
  'Plaza Mayor de La Jana, Castellon',
  'active'
),
(
  'Albufera al atardecer en barca',
  'albufera-atardecer-barca',
  'Navega en barca tradicional por la Albufera de Valencia al atardecer y disfruta de una paella autentica.',
  'Embarcate en una experiencia magica: surcaras las aguas de la Albufera de Valencia en una barca de pesca tradicional (un "barquet") mientras el sol se pone sobre el lago, pintando el cielo de naranjas y rojos. Un barquero local te contara la historia de este humedal protegido, avistaras aves como garzas, flamencos y el calamón comun. Al regresar a tierra, disfrutaras de una autentica paella valenciana cocinada a lena en una barraca junto al lago. Maridaje con vinos de la DO Valencia incluido.',
  (select id from public.regions where slug = 'comunidad-valenciana'),
  (select id from public.categories where slug = 'ecoturismo'),
  6900,
  7900,
  4,
  10,
  4,
  4.8,
  156,
  true,
  true,
  'https://images.unsplash.com/photo-1500259571355-332da5cb07aa?w=800&q=80',
  array['https://images.unsplash.com/photo-1500259571355-332da5cb07aa?w=800&q=80', 'https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?w=800&q=80'],
  array['Paseo en barca tradicional', 'Guia ornitologico', 'Prismaticos', 'Paella valenciana a lena', 'Vinos DO Valencia', 'Seguro de actividad'],
  array['Transporte al embarcadero', 'Bebidas extra'],
  array['Atardecer sobre la Albufera', 'Paella a lena autentica', 'Avistamiento de aves', 'Barca tradicional valenciana'],
  'Embarcadero de El Palmar, Valencia',
  'active'
),
(
  'Ruta de tapas en el Casco Viejo de Bilbao',
  'ruta-tapas-bilbao',
  'Descubre los pintxos mas autenticos del Casco Viejo de Bilbao con un chef local como guia.',
  'Sumérgete en la cultura gastronomica vasca de la mano de un chef local que te guiara por 6 de los mejores bares de pintxos del Casco Viejo de Bilbao. Probaras desde el clasico "gilda" hasta creaciones de alta cocina en miniatura, todo maridado con txakoli, vino de Rioja Alavesa y sidra natural. Aprenderas la historia de cada pintxo, las reglas no escritas de la cultura de barra y visitaras la Plaza Nueva y el Mercado de la Ribera, el mercado cubierto mas grande de Europa. Una experiencia para los sentidos.',
  (select id from public.regions where slug = 'pais-vasco'),
  (select id from public.categories where slug = 'gastronomia'),
  7900,
  null,
  3,
  10,
  18,
  4.9,
  198,
  true,
  false,
  'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=800&q=80',
  array['https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=800&q=80', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80'],
  array['6 paradas gastronomicas', 'Pintxos y raciones en cada parada', 'Bebida en cada parada (txakoli, vino, sidra)', 'Guia chef local', 'Visita al Mercado de la Ribera'],
  array['Bebidas adicionales', 'Transporte'],
  array['6 bares de pintxos autenticos', 'Chef local como guia', 'Mercado de la Ribera', 'Txakoli y sidra natural'],
  'Plaza Nueva de Bilbao, junto a la Oficina de Turismo',
  'active'
),
(
  'Donana: safari en 4x4 y avistamiento de aves',
  'donana-safari-aves',
  'Explora el Parque Nacional de Donana en vehiculo todoterreno con un ornitologo experto.',
  'Adentrarte en el corazon del Parque Nacional de Donana, la mayor reserva ecologica de Europa, en un safari exclusivo en 4x4. Durante 6 horas, un ornitologo certificado te guiara por marismas, dunas y bosques de pinos donde podras avistar linces ibericos (con suerte), flamencos, aguilas imperiales y ciervos. Visitaras la aldea de El Rocio y las famosas marismas al atardecer. Incluye almuerzo en un cortijo andaluz con productos de la zona. Grupos reducidos para minimizar el impacto ambiental.',
  (select id from public.regions where slug = 'andalucia'),
  (select id from public.categories where slug = 'ecoturismo'),
  8900,
  9900,
  6,
  8,
  8,
  4.7,
  92,
  false,
  false,
  'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80',
  array['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80', 'https://images.unsplash.com/photo-1557456170-0cf4f4d0d362?w=800&q=80'],
  array['Vehiculo 4x4 exclusivo', 'Ornitologo certificado', 'Prismaticos y guia de aves', 'Almuerzo en cortijo', 'Seguro de actividad'],
  array['Transporte hasta el punto de encuentro', 'Proteccion solar y sombrero'],
  array['Parque Nacional de Donana', 'Posible avistamiento de lince iberico', 'Flamencos y aguilas imperiales', 'Almuerzo en cortijo andaluz'],
  'Centro de visitantes El Acebuche, Huelva',
  'active'
),
(
  'Retiro de bienestar en cortijo andaluz',
  'retiro-bienestar-cortijo',
  'Un dia de desconexion total: yoga al amanecer, bano en piscina natural y cocina saludable con huerto propio.',
  'Escapa de la rutina con un dia de bienestar integral en un cortijo restaurado del siglo XVIII en las Alpujarras granadinas. Comenzaras con una sesion de yoga al amanecer en la terraza con vistas a Sierra Nevada, seguida de una meditacion guiada entre olivos. Despues, disfrutaras de un taller de cocina saludable con ingredientes del huerto ecologico del cortijo. El almuerzo sera tu propia creacion. Por la tarde, bano en la piscina natural de roca y masaje relajante con aceites esenciales de lavanda local.',
  (select id from public.regions where slug = 'andalucia'),
  (select id from public.categories where slug = 'bienestar'),
  11900,
  null,
  10,
  8,
  16,
  5.0,
  34,
  false,
  false,
  'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
  array['https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80', 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80'],
  array['Sesion de yoga y meditacion', 'Taller de cocina saludable', 'Almuerzo con productos del huerto', 'Masaje relajante 30min', 'Acceso a piscina natural', 'Esterilla y material de yoga'],
  array['Transporte al cortijo', 'Ropa de bano'],
  array['Yoga con vistas a Sierra Nevada', 'Cocina con huerto ecologico', 'Masaje con aceites locales', 'Piscina natural de roca'],
  'Cortijo Los Almendros, Capileira, Granada',
  'active'
)
on conflict (slug) do nothing;
